{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svgui
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/svGUI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svGUI/svGUI_{{ version }}.tar.gz
  sha256: e9a477b41276b8c4b5040b594fad1ddf8173481ff5f63d78929d0c345d7b0532

build:
  noarch: generic 
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('svGUI')"           # [not win]
    - "\"%R%\" -e \"library('svGUI')\""  # [win]

about:
  home: https://github.com/SciViews/svGUI, http://www.sciviews.org/SciViews-R
  license: GPL-2.0-only
  summary: The SciViews svGUI package eases the management of Graphical User Interfaces (GUI) in R. It is independent from any particular GUI widgets (Tk, Gtk2, native, ...). It centralizes info about GUI elements currently used, and it dispatches GUI calls to the particular toolkits in use in function of the context (is
    R run at the terminal, within a Tk application, a HTML page?).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
