# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LbcusQ90os0wBXDg/+nUSw+8PlNwx5fpMLGewhVgUBmjNZFmznTbrLuLR2qYtpzd14UazDnrgWokk8Hn5O79bzpsIkGMesst5PPpDU/mwYY4Lgbo8U3unvquTcakXpEPSPUCWxcn91VRPXnyoiTJ+1a0Mo3OPinmVz1xlhciQza7nxRnfnDcSOcAw/msRcFSTFEIYWAaOn+4BeCLVvSDtMnTsBMlnXheOCZlqb5LUuLkTNELWol0mUBpmXJDhDDMElTBOVWC6KTFxUtdEpW+g8PhUwxQdDQ1hQ5P8BK/KlK17+HpF5JUxTLDLrrD7llEy0CDNqrbKHE2e4/uDAICtY6/TJFb/rZV1RQcDtiGuKG0X1fVlwVJ+AvaKa1D13yQUUGZdjyoirC6D/UyDEx160xR52wjIyhVvSkCzAjFIg8Vj68rIhxCSWc134M7rLqTXMefD7jK7Z/XHROoyLI5BRumYknpJ4yKMdPMLrsc9eqhZL1ZL5WgsO87mphuu423ewacaK11MbME2ALvFkvMdnNi36Vs8obM/Ltm6fMrMSIyxlWZNb/Gg+iHWJ06WImnJNcC2EQ2hXJZmhuydWAlR3I93qC3FrJyZeC1nuwuz9Ef+dFvNykXvF3pMbbl85KLG9Jx4dTqv+UeNiGec/ZbeTs1k3AYxYsdqff8QH0L7+U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
