appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LbcusQ90os0wBXDg/+nUSw+8PlNwx5fpMLGewhVgUBmjNZFmznTbrLuLR2qYtpzd14UazDnrgWokk8Hn5O79bzpsIkGMesst5PPpDU/mwYY4Lgbo8U3unvquTcakXpEPSPUCWxcn91VRPXnyoiTJ+1a0Mo3OPinmVz1xlhciQza7nxRnfnDcSOcAw/msRcFSTFEIYWAaOn+4BeCLVvSDtMnTsBMlnXheOCZlqb5LUuLkTNELWol0mUBpmXJDhDDMElTBOVWC6KTFxUtdEpW+g8PhUwxQdDQ1hQ5P8BK/KlK17+HpF5JUxTLDLrrD7llEy0CDNqrbKHE2e4/uDAICtY6/TJFb/rZV1RQcDtiGuKG0X1fVlwVJ+AvaKa1D13yQUUGZdjyoirC6D/UyDEx160xR52wjIyhVvSkCzAjFIg8Vj68rIhxCSWc134M7rLqTXMefD7jK7Z/XHROoyLI5BRumYknpJ4yKMdPMLrsc9eqhZL1ZL5WgsO87mphuu423ewacaK11MbME2ALvFkvMdnNi36Vs8obM/Ltm6fMrMSIyxlWZNb/Gg+iHWJ06WImnJNcC2EQ2hXJZmhuydWAlR3I93qC3FrJyZeC1nuwuz9Ef+dFvNykXvF3pMbbl85KLG9Jx4dTqv+UeNiGec/ZbeTs1k3AYxYsdqff8QH0L7+U=}
