travis:
  secure:
    BINSTAR_TOKEN: j2Fcu9sXlGO1eBKdPni155ulCmOhMVWtFXnI+j04EyynpIvlxqFHsPBnQiixgSHfTeZS9enW8jmeVuSSmTKZ07wDLx/zv4hpouxAEuEimD6qfLZJTjXc3X+DliyeYOXPBmjYxcl3B+Bgqnxsa9tPhj/leLdr8KW3kGiDdxv7w23ScrM+hW7Igh47S+7l2uEBj6Zq+NCrYXndrc+OyV4hXLcyKBOrAihMq24uebP3bqkLP21MgNy62NIpGDBIeeeoDq11fdRoFeOK9Fi09aj3CbG7kuWaIpU/DavmJSLcPmlLRqqPZ5eJ61l1nVtxUbCQEbBTyIvC8duJ1iw+pWpMQlRv6HrVZisSR1vmC49Dq1qpqeO6edh5w5u80/FZIDbU8Z24owUAFq8d7JLCuwYMnlZdchd9JhlC0WcKmI87SBsF7tSHIP8H02PlgBejXpvpwNlHCRUGnQ0faw24pb0V9OqOuYoUBb4HghiwmjcSjFONXegkSweOFyKslvQ1gS0dG1t2x/DQZ2qR5dGcwiI9fj56b6jrQhR1x4Wewbj7IjD3nHrOM9+HLNNj4rgE/yuBOQ5s1XaMH/GjM3zCSygUADe5n3SIlYaz8u0qnF+hxxuuXh6cAUdhnMoNKL+EhjVPX5I0ByrqNQvUGfNRd95HvT/CuoU1tzK1JmslVH5L3+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
